using CommandLine;

namespace TiledToLB.CLI.CommandLine
{
    [Verb("create", HelpText = "Creates a new Tiled tmx file along with an extra tileset")]
    public class CreateNewOptions : BaseOptions
    {
        [Option('w', "workspace", Required = true, HelpText = "The directory generated by unpacking. The map will be placed into the \"Maps\" folder")]
        public required string WorkspaceDirectoryPath { get; set; }

        [Option('n', "name", Required = true, HelpText = "The desired name of the map")]
        public required string MapName { get; set; }

        [Option('c', "creator", Required = false, HelpText = "The desired name of the creator")]
        public string CreatorName { get; set; } = string.Empty;

        [Option('t', "tileset", Required = true, HelpText = "The name of the tileset to use. \"King\", \"Mars\", or \"Pirate\"")]
        public required string TilesetName { get; set; }
    }
}
