using CommandLine;

namespace TiledToLB.CLI.CommandLine
{
    [Verb("export-lbz", HelpText = "Processes a .tmx file into multiple files to be patched into the ROM")]
    public class ExportLBZOptions : BaseOptions
    {
        [Option('w', "workspace", Required = true, HelpText = "The directory generated by unpacking. The map will be placed into the \"Output\" folder")]
        public required string WorkspaceDirectoryPath { get; set; }

        [Option('o', "output", Required = true, HelpText = "The desired name of the map's output files")]
        public required string OutputMapName { get; set; }

        [Option('i', "input", Required = true, HelpText = "The input tmx file name, which should be within the \"Maps\" folder")]
        public required string InputMapName { get; set; }
    }
}
