using CommandLine;

namespace TiledToLB.CLI.CommandLine
{
    [Verb("import-rom", HelpText = "Imports a map from the given game rom and processes it into a .tmx file")]
    public class ImportFromRomOptions : BaseOptions
    {
        [Option('w', "workspace", Required = true, HelpText = "The directory generated by unpacking. The map will be placed into the \"Maps\" folder")]
        public required string WorkspaceDirectoryPath { get; set; }

        [Option('i', "input", Required = true, HelpText = "The input rom file")]
        public required string InputFilePath { get; set; }

        [Option('m', "map", Required = true, HelpText = "The map's file name inside the rom, such as \"ck1_1\"")]
        public required string RomMapName { get; set; }

        [Option('o', "output", Required = true, HelpText = "The desired name of the map's output files")]
        public required string OutputMapName { get; set; }
    }
}
